### ISSUE TITLE
[doc request] How to build CTA templates

### ISSUE THREAD

**Issue by pedrohrezende** [inboundnow/cta#107]
Hello, the templating framework link is broken.
I'm trying to build a template, but a can't acess the documentation :(

**Comment by atwellpub** [comment]
Hi @pedrohrezende 

I'm not sure we've built documentation for CTA templates, and at the moment have left developers to study currently built templates in order to learn how to build their own. 

Template building is not too difficult. Here is an example:

https://github.com/inboundnow/cta/blob/master/templates/demo/


### config.php

This file sets up the dynamic settings.

### index.php 

This file is read into config.php at this line:
https://github.com/inboundnow/cta/blob/master/templates/demo/config.php#L191

We use special shorthand logic tokens to replace PHP if/else statements. Inside the file there are examples on how to use the shorthand token logic.
https://github.com/inboundnow/cta/blob/master/templates/demo/index.php

Please feel free to ask questions and examples here, we'll use this thread to build up an official documentation document.

**Comment by atwellpub** [comment]
Added a foundation: 

http://docs.inboundnow.com/guide/how-to-create-custom-call-to-action-templates/

**Comment by DavidWells** [comment]
Good doc.

We need to roll out ACF fields (not tokens) for CTA

Then we can have a single doc for all template creation (with tiny sections
for cta/email/lp specifics)
