### ISSUE TITLE
Link 404

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#112]
Have you seen this problem before? https://wordpress.org/support/topic/links-not-working-104?replies=1

**Comment by atwellpub** [comment]
Have, doesn't happen very often since last version because of prompts to save permalinks if they are still set to default. There's also a programtic measure to flush the permalinks after activation, but if permalinks are set to default it still won't set the handlers. 

Saving permalinks should fix the issue. Will keep an eye on the ticket.

**Comment by atwellpub** [comment]
https://github.com/inboundnow/cta/commit/8d727b74b3c60d990d58ef4ad3844e54944e7d86
