### ISSUE TITLE
Code Q

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#124]
What is this supposed to do? https://github.com/inboundnow/cta/blob/master/classes/class.cta.render.php#L1031

It equals display = "none" no matter what

**Comment by atwellpub** [comment]
Looks like it's not needed. But I'd leave it in, it might become a preferential way to display the correct variation in the future. It looks like it was designed to immediately reveal it instead of relying on ajax during a preview but somewhere along the line I noticed it wasn't working correctly, didn't notice that mistake, and used another path to reveal the preview (I think... I'm not positive).
